
cloud1 :
    domains:
        DockerNode1:
            #day_of_week: [Sun, Mon, Tue, Wed, Thu, Fri, Sat]
            day_of_week: [Sun]
            rotate: 4
            
        DockerNode2:
            day_of_week: [Sun]
            rotate: 4
            
    backupdir: /mnt/cloud/kvm_backup/cloud1
    
cloud2 :
    domains:
        core:
            day_of_week: [Sun]
            rotate: 4

    backupdir: /mnt/dell_storage/cloud/kvm_backup/cloud2
    
cloud3 :
    domains:
        webserverslave4:
            day_of_week: [Sun]
            rotate: 4
    backupdir: /mnt/dell_storage/cloud/kvm_backup/cloud3
    
